/*
 * category.h
 *
 *  Created on: 12 Feb 2014
 *      Author: zytka
 */

#ifndef _SAFEKIDDO_CATEGORY_H_
#define _SAFEKIDDO_CATEGORY_H_

namespace safekiddo
{
namespace webroot
{

enum Category
{
	REAL_ESTATE = 1,
	COMPUTER_AND_INTERNET_SECURITY = 2,
	FINANCIAL_SERVICES = 3,
	BUSINESS_AND_ECONOMY = 4,
	COMPUTER_AND_INTERNET_INFO = 5,
	AUCTIONS = 6,
	SHOPPING = 7,
	CULT_AND_OCCULT = 8,
	TRAVEL = 9,
	ABUSED_DRUGS = 10,
	ADULT_AND_PORNOGRAPHY = 11,
	HOME_AND_GARDEN = 12,
	MILITARY = 13,
	SOCIAL_NETWORK = 14,
	DEAD_SITES_DB_OPS_ONLY = 15,
	INDIVIDUAL_STOCK_ADVICE_AND_TOOLS = 16,
	TRAINING_AND_TOOLS = 17,
	DATING = 18,
	SEX_EDUCATION = 19,
	RELIGION = 20,
	ENTERTAINMENT_AND_ARTS = 21,
	PERSONAL_SITES_AND_BLOGS = 22,
	LEGAL = 23,
	LOCAL_INFORMATION = 24,
	STREAMING_MEDIA = 25,
	JOB_SEARCH = 26,
	GAMBLING = 27,
	TRANSLATION = 28,
	REFERENCE_AND_RESEARCH = 29,
	SHAREWARE_AND_FREEWARE = 30,
	PEER_TO_PEER = 31,
	MARIJUANA = 32,
	HACKING = 33,
	GAMES = 34,
	PHILOSOPHY_AND_POLITICAL_ADVOCACY = 35,
	WEAPONS = 36,
	PAY_TO_SURF = 37,
	HUNTING_AND_FISHING = 38,
	SOCIETY = 39,
	EDUCATIONAL_INSTITUTIONS = 40,
	ONLINE_GREETING_CARDS = 41,
	SPORTS = 42,
	SWIMSUITS_AND_INTIMATE_APPAREL = 43,
	QUESTIONABLE = 44,
	KIDS = 45,
	HATE_AND_RACISM = 46,
	ONLINE_PERSONAL_STORAGE = 47,
	VIOLENCE = 48,
	KEYLOGGERS_AND_MONITORING = 49,
	SEARCH_ENGINES = 50,
	INTERNET_PORTALS = 51,
	WEB_ADVERTISEMENTS = 52,
	CHEATING = 53,
	GROSS = 54,
	WEB_BASED_EMAIL = 55,
	MALWARE_SITES = 56,
	PHISHING_AND_OTHER_FRAUDS = 57,
	PROXY_AVOIDANCE_AND_ANONYMIZERS = 58,
	SPYWARE_AND_ADWARE = 59,
	MUSIC = 60,
	GOVERNMENT = 61,
	NUDITY = 62,
	NEWS_AND_MEDIA = 63,
	ILLEGAL = 64,
	CONTENT_DELIVERY_NETWORKS = 65,
	INTERNET_COMMUNICATIONS = 66,
	BOT_NETS = 67,
	ABORTION = 68,
	HEALTH_AND_MEDICINE = 69,
	CONFIRMED_SPAM_SOURCES = 70,
	SPAM_URLS = 71,
	UNCONFIRMED_SPAM_SOURCES = 72,
	OPEN_HTTP_PROXIES = 73,
	DYNAMICALLY_GENERATED_CONTENT = 74,
	PARKED_DOMAINS = 75,
	ALCOHOL_AND_TOBACCO = 76,
	PRIVATE_IP_ADDRESSES = 77,
	IMAGE_AND_VIDEO_SEARCH = 78,
	FASHION_AND_BEAUTY = 79,
	RECREATION_AND_HOBBIES = 80,
	MOTOR_VEHICLES = 81,
	WEB_HOSTING = 82
};

std::ostream & operator<<(std::ostream & os, Category category);

} // webroot
} // safekiddo

#endif /* _SAFEKIDDO_CATEGORY_H_ */
