insert into categories(ext_id, name, code_categories_groups_id) values(1,'Real Estate',1);
insert into categories(ext_id, name, code_categories_groups_id) values(2,'Computer and Internet Security',9);
insert into categories(ext_id, name, code_categories_groups_id) values(3,'Financial Services',1);
insert into categories(ext_id, name, code_categories_groups_id) values(4,'Business and Economy',1);
insert into categories(ext_id, name, code_categories_groups_id) values(5,'Computer and Internet Info',9);
insert into categories(ext_id, name, code_categories_groups_id) values(6,'Auctions',22);
insert into categories(ext_id, name, code_categories_groups_id) values(7,'Shopping',22);
insert into categories(ext_id, name, code_categories_groups_id) values(8,'Cult and Occult',11);
insert into categories(ext_id, name, code_categories_groups_id) values(9,'Travel',15);
insert into categories(ext_id, name, code_categories_groups_id) values(10,'Abused Drugs',3);
insert into categories(ext_id, name, code_categories_groups_id) values(11,'Adult and Pornography',3);
insert into categories(ext_id, name, code_categories_groups_id) values(12,'Home and Garden',1);
insert into categories(ext_id, name, code_categories_groups_id) values(13,'Military',7);
insert into categories(ext_id, name, code_categories_groups_id) values(14,'Social Networking',16);
insert into categories(ext_id, name, code_categories_groups_id) values(16,'Individual Stock Advice and Tools',5);
insert into categories(ext_id, name, code_categories_groups_id) values(17,'Training and Tools',1);
insert into categories(ext_id, name, code_categories_groups_id) values(18,'Dating',18);
insert into categories(ext_id, name, code_categories_groups_id) values(19,'Sex Education',18);
insert into categories(ext_id, name, code_categories_groups_id) values(20,'Religion',19);
insert into categories(ext_id, name, code_categories_groups_id) values(21,'Entertainment and Arts',1);
insert into categories(ext_id, name, code_categories_groups_id) values(22,'Personal sites and Blogs',20);
insert into categories(ext_id, name, code_categories_groups_id) values(23,'Legal',5);
insert into categories(ext_id, name, code_categories_groups_id) values(24,'Local Information',1);
insert into categories(ext_id, name, code_categories_groups_id) values(25,'Streaming Media',10);
insert into categories(ext_id, name, code_categories_groups_id) values(26,'Job Search',17);
insert into categories(ext_id, name, code_categories_groups_id) values(27,'Gambling',3);
insert into categories(ext_id, name, code_categories_groups_id) values(28,'Translation',1);
insert into categories(ext_id, name, code_categories_groups_id) values(29,'Reference and Research',1);
insert into categories(ext_id, name, code_categories_groups_id) values(30,'Shareware and Freeware',9);
insert into categories(ext_id, name, code_categories_groups_id) values(31,'Peer to Peer',10);
insert into categories(ext_id, name, code_categories_groups_id) values(32,'Marijuana',3);
insert into categories(ext_id, name, code_categories_groups_id) values(33,'Hacking',8);
insert into categories(ext_id, name, code_categories_groups_id) values(34,'Games',6);
insert into categories(ext_id, name, code_categories_groups_id) values(35,'Philosophy and Political Advocacy',4);
insert into categories(ext_id, name, code_categories_groups_id) values(36,'Weapons',3);
insert into categories(ext_id, name, code_categories_groups_id) values(37,'Pay to Surf',8);
insert into categories(ext_id, name, code_categories_groups_id) values(38,'Hunting and Fishing',12);
insert into categories(ext_id, name, code_categories_groups_id) values(39,'Society',4);
insert into categories(ext_id, name, code_categories_groups_id) values(40,'Educational Institutions',1);
insert into categories(ext_id, name, code_categories_groups_id) values(41,'Online Greeting cards',1);
insert into categories(ext_id, name, code_categories_groups_id) values(42,'Sports',7);
insert into categories(ext_id, name, code_categories_groups_id) values(43,'Swimsuits & Intimate Apparel',24);
insert into categories(ext_id, name, code_categories_groups_id) values(44,'Questionable',3);
insert into categories(ext_id, name, code_categories_groups_id) values(45,'Kids',2);
insert into categories(ext_id, name, code_categories_groups_id) values(46,'Hate and Racism',3);
insert into categories(ext_id, name, code_categories_groups_id) values(47,'Personal Storage',9);
insert into categories(ext_id, name, code_categories_groups_id) values(48,'Violence',3);
insert into categories(ext_id, name, code_categories_groups_id) values(49,'Keyloggers and Monitoring',8);
insert into categories(ext_id, name, code_categories_groups_id) values(50,'Search Engines',28);
insert into categories(ext_id, name, code_categories_groups_id) values(51,'Internet Portals',20);
insert into categories(ext_id, name, code_categories_groups_id) values(52,'Web Advertisements',9);
insert into categories(ext_id, name, code_categories_groups_id) values(53,'Cheating',24);
insert into categories(ext_id, name, code_categories_groups_id) values(54,'Gross',24);
insert into categories(ext_id, name, code_categories_groups_id) values(55,'Web based email',14);
insert into categories(ext_id, name, code_categories_groups_id) values(56,'Malware Sites',26);
insert into categories(ext_id, name, code_categories_groups_id) values(57,'Phishing and Other Frauds',26);
insert into categories(ext_id, name, code_categories_groups_id) values(58,'Proxy Avoidance and Anonymizers',8);
insert into categories(ext_id, name, code_categories_groups_id) values(59,'Spyware and Adware',8);
insert into categories(ext_id, name, code_categories_groups_id) values(60,'Music',7);
insert into categories(ext_id, name, code_categories_groups_id) values(61,'Government',1);
insert into categories(ext_id, name, code_categories_groups_id) values(62,'Nudity',3);
insert into categories(ext_id, name, code_categories_groups_id) values(63,'News and Media',21);
insert into categories(ext_id, name, code_categories_groups_id) values(64,'Illegal',3);
insert into categories(ext_id, name, code_categories_groups_id) values(65,'Content Delivery Networks',1);
insert into categories(ext_id, name, code_categories_groups_id) values(66,'Internet Communications',10);
insert into categories(ext_id, name, code_categories_groups_id) values(67,'Bot Nets',26);
insert into categories(ext_id, name, code_categories_groups_id) values(68,'Abortion',3);
insert into categories(ext_id, name, code_categories_groups_id) values(69,'Health and Medicine',23);
insert into categories(ext_id, name, code_categories_groups_id) values(71,'SPAM URLs',26);
insert into categories(ext_id, name, code_categories_groups_id) values(74,'Dynamically Generated Content',10);
insert into categories(ext_id, name, code_categories_groups_id) values(75,'Parked Domains',8);
insert into categories(ext_id, name, code_categories_groups_id) values(76,'Alcohol and Tobacco',3);
insert into categories(ext_id, name, code_categories_groups_id) values(77,'Private IP Addresses',25);
insert into categories(ext_id, name, code_categories_groups_id) values(78,'Image and Video Search',10);
insert into categories(ext_id, name, code_categories_groups_id) values(79,'Fashion and Beauty',13);
insert into categories(ext_id, name, code_categories_groups_id) values(80,'Recreation and Hobbies',7);
insert into categories(ext_id, name, code_categories_groups_id) values(81,'Motor Vehicles',1);
insert into categories(ext_id, name, code_categories_groups_id) values(82,'Web Hosting',9);
insert into categories(ext_id, name, code_categories_groups_id) values(15,'Dead Sites',27);

